subdir('boot')
subdir('drivers')
subdir('dynamic')
subdir('kernel')
subdir('lib')
subdir('shell')

pongo_sources_c = [
  pongo_boot_sources_c,
  pongo_drivers_aes_sources_c,
  pongo_drivers_dt_sources_c,
  pongo_drivers_framebuffer_sources_c,
  pongo_drivers_fuse_sources_c,
  pongo_drivers_gpio_sources_c,
  pongo_drivers_hal_sources_c,
  pongo_drivers_mipi_sources_c,
  pongo_drivers_plat_sources_c,
  pongo_drivers_recfg_sources_c,
  pongo_drivers_sep_sources_c,
  pongo_drivers_timer_sources_c,
  pongo_drivers_tz_sources_c,
  pongo_drivers_uart_sources_c,
  pongo_drivers_usb_sources_c,
  pongo_drivers_xnu_sources_c,
  pongo_dynamic_sources_c,
  pongo_kernel_sources_c,
  pongo_kernel_support_sources_c,
  pongo_lib_img4_sources_c,
  pongo_lib_libder_sources_c,
  pongo_lib_lzma_sources_c,
  pongo_shell_sources_c,
]

pongo_sources_asm = [
  pongo_boot_sources_asm,
  pongo_drivers_sep_sources_asm,
  pongo_drivers_xnu_sources_asm,
  pongo_kernel_sources_asm,
]
