subdir('support')

pongo_kernel_sources_c = [
  'src/pongo/kernel/entry.c',
  'src/pongo/kernel/legacy.c',
  'src/pongo/kernel/locks.c',
  'src/pongo/kernel/lowlevel.c',
  'src/pongo/kernel/main_task.c',
  'src/pongo/kernel/mm.c',
  'src/pongo/kernel/panic.c',
  'src/pongo/kernel/syscall.c',
  'src/pongo/kernel/task.c',
  'src/pongo/kernel/vfs.c',
]

pongo_kernel_sources_asm = [
  'src/pongo/kernel/int.S',
]
