pongo_drivers_plat_sources_c = [
  'src/pongo/drivers/plat/s5l8960.c',
  'src/pongo/drivers/plat/s8000.c',
  'src/pongo/drivers/plat/s8001.c',
  'src/pongo/drivers/plat/s8003.c',
  'src/pongo/drivers/plat/t7000.c',
  'src/pongo/drivers/plat/t7001.c',
  'src/pongo/drivers/plat/t8010.c',
  'src/pongo/drivers/plat/t8011.c',
  'src/pongo/drivers/plat/t8012.c',
  'src/pongo/drivers/plat/t8015.c',
]
